[Refactor] #181. 프론트의 MainScreen이 빌드되는 시간이 오래 걸리는 문제
Kernel360/E2E1-Orury pull request #186
Opened 2023-11-23 14:01 UTC by mooncw

## 개요
게시글 목록 화면에서 api 응답을 받는데 오래 걸려서 원인으로 예상되는 쿼리쪽 오버헤드를 줄이기 위한 코드 리팩토링

### 상세 내용
- 최대한 필요한 데이터만 db에서 꺼내서 api 응답으로 보낼 수 있게 코드를 수정하여 기존의 오버헤드 비용을 줄임
- 엔티티는 OneToMany는 제거하고 ManyToOne은 그대로 유지
- post_list나 comment_list는 필요할 때 jpa 쿼리로 꺼내오는 형식으로 변경
- 프런트엔드 보충

Resolves: #181 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [x] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://quickest-asterisk-75d.notion.site/2a977a0d71db4062bc705dc199ebff13?pvs=4).
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2023-11-23 14:30 UTC, kkkapuq requested changes
구두상으로 말씀드린대로, toDto를 그대로 쓰기 위해 bool 값을 flag parameter로 넘기는 것은 부적합한 것 같습니다.
if문이 추가되서 복잡해질뿐더러, 다른사람이 봤을 때 bool 값이 왜 들어갔는지 이해하기가 힘들 것 같습니다.

게시판 전체를 조회했을 때, 하위 Entity인 post와 comment들은 불러오지 않는 함수
ex) toDtoOnlyBoard()
로 따로 빼서, `모든 게시판 요청 api`에만 사용하도록 하는 것이 더 좋은 코드가 될 것 같습니다.

2023-11-24 05:34 UTC, ShineCorine approved these changes

2023-11-24 05:59 UTC, aqrms approved these changes
LGTM

2023-11-24 06:00 UTC, kkkapuq approved these changes
수고하셨습니다.
@oneToMany 없애는 것 대신
뭔가 더 좋은 방법이 있을 것 같은데.. JPA를 잘 몰라서 아쉽네요

2023-11-24 06:00 UTC, merged